# Generated by Django 2.1.5 on 2019-01-14 00:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=150)),
                ('taskImportance', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('doneDate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('createDatetime', models.DateTimeField(auto_now_add=True)),
                ('updateDatetime', models.DateTimeField(auto_now=True)),
                ('completedDatetime', models.DateTimeField(blank=True, null=True)),
                ('taskOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
